services:
  - type: web
    name: game-server
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    numInstances: 1
    envVars:
      - key: PORT
        value: 8080
    healthCheckPath: /