name: Deploy Snake Game

on:
  push:
    branches:
      - main  # 监听 main 分支的推送事件

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 设置 Node.js 环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 安装依赖
      - name: Install dependencies
        run: npm install

      # 打包文件（可选）
      - name: Package files
        run: |
          tar -czf snake-game.tar.gz index.html server.js package.json package-lock.json update_my_service.sh Dockerfile

      # 推送文件到服务器
      - name: Deploy to Server
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_PASSWORD: ${{ secrets.DEPLOY_PASSWORD }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          echo "Deploying to $DEPLOY_SERVER..."
          sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
            mkdir -p $DEPLOY_PATH
            exit
          EOF
          sshpass -p $DEPLOY_PASSWORD scp -o StrictHostKeyChecking=no snake-game.tar.gz $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH
          sshpass -p $DEPLOY_PASSWORD ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER << 'EOF'
            cd $DEPLOY_PATH
            tar -xzf snake-game.tar.gz
            rm snake-game.tar.gz
            curl -X POST -H "Content-Type: application/json" -d '{"event":"deploy"}' http://$DEPLOY_SERVER:9000/hooks/deploy
            exit
          EOF